name: Run

run-name: Run

on:
  workflow_dispatch: 
    inputs:
      component:
        description: component - a;m;s1;s2;s3

jobs:
  main:
    name: "Main"
    runs-on: ubuntu-latest

    outputs:
      s1: ${{ steps.components.outputs.s1 }}
      s2: ${{ steps.components.outputs.s2 }}
      s3: ${{ steps.components.outputs.s3 }}

    steps:
      - uses: actions/checkout@v4
      
      - name: "test main"
        run: echo running main

      - name: specify components
        id: components
        env:
          COMPONENT: ${{ github.event.inputs.component }}
        run: |
          node generate.js
          echo "s1=$(jq '.s1' env.json)" >> $GITHUB_ENV
          echo "s2=$(jq '.s2' env.json)" >> $GITHUB_ENV
          echo "s3=$(jq '.s3' env.json)" >> $GITHUB_ENV

  s1:
    needs: main
    if: ${{ needs.main.outputs.s1  == 'enabled' }}
    name: "component s1"
    runs-on: ubuntu-latest

    env:
      COMPONENT: ${{ github.event.inputs.component }}

    steps:
      - name: "run component s1"
        run: echo running component s1 for $COMPONENT

  s2:
    needs: main
    if: ${{ needs.main.outputs.s2  == 'enabled' }}
    name: "component s2"
    runs-on: ubuntu-latest

    env:
      COMPONENT: ${{ github.event.inputs.component }}

    steps:
      - name: "run component s2"
        run: echo running component s2 for $COMPONENT

  s3:
    needs: main
    if: ${{ needs.main.outputs.s3  == 'enabled' }}
    name: "component s3"
    runs-on: macos-latest

    env:
      COMPONENT: ${{ github.event.inputs.component }}

    steps:
      - name: "run component s3"
        run: echo running component s3 for $COMPONENT