name: Run

run-name: Run

on:
  push:
    branches:
      - "main"


jobs:
  run:
    name: "Runn"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Start docker compose
        run: docker compose -f sit/docker-compose.yml up -d --wait

      - name: Test
        run: curl localhost:8085/connections

      - name: Stop
        run: docker compose -f sit/docker-compose.yml down